root = "."
tmp_dir = "tmp"

[build]
# Windows configuration:
# cmd = "go build -o ./tmp/main.exe ./src"
# bin = "tmp/main.exe" 

# Mac/Linux configuration (comment above, uncomment below when on Mac/Linux):
cmd = "go build -o ./tmp/main ./cmd/app"
bin = "tmp/main"

include_ext = ["go", "env"]
exclude_dir = ["tmp", "vendor", "testdata"]
exclude_regex = ["_test\\.go$"]
delay = 1000

[log]
time = true
main_only = false

[screen]
clear_on_rebuild = true

[misc]
clean_on_exit = true
